name: ASP.NET CI
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1

    - name: build
      working-directory: Our.Umbraco.CloudPurge
      run: dotnet build
