name: ASP.NET CI
on: [push]
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    - name: MSBuild
      working-directory: Our.Umbraco.CloudPurge
      run: msbuild Our.Umbraco.CloudPurge.csproj
